apiVersion: v1
kind: Service
metadata:
  name: sfgtomcat-svc
  labels:
    app: sfgtomcat-svc
  namespace: default
spec:
  ports:
    - port: 80
      targetPort: 8080     
  selector:
    k8s-app: sfgtomcat    
 
 