apiVersion: v1
kind: PersistentVolume
metadata: 
  name: ceph-pv
spec: 
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  rbd: 
    monitors: 
      - 192.168.15.52:6789      
    pool: test
    image: myvol
    user: admin
    secretRef: 
      name: ceph-secret
    fsType: ext4
    readOnly: false