apiVersion: v1
kind: Pod
metadata: 
  name: ceph-mysql
spec: 
  containers: 
    - name: ceph-mysql
      image: tutum/mysql
      ports:
        - name: mysql-db
          containerPort: 3306
      volumeMounts: 
        - name: mysql-pv
          mountPath: /var/lib/mysql
  volumes: 
    - name: mysql-pv
      persistentVolumeClaim:
        claimName: ceph-claim