kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-pv
  labels:
    type: local
spec:
  storageClassName: mysql-sc
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mysqldata"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: myappdb-mysql
spec:
  storageClassName:  mysql-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi    