kind: PersistentVolume
apiVersion: v1
metadata:
  name: kafka-pv-volume
  labels:
    type: local
spec:
  storageClassName: kafka-sc
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/kubeless/kafka"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: datadir-kafka-0
spec:
  storageClassName:  kafka-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi    