kind: PersistentVolume
apiVersion: v1
metadata:
  name: zookeeper-pv-volume
  labels:
    type: local
spec:
  storageClassName: zookeeper-sc
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/kubeless/zookeeper"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zookeeper-zoo-0
spec:
  storageClassName:  zookeeper-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi    