kind: PersistentVolume
apiVersion: v1
metadata:
  name: mnio-pv-volume  
spec: 
  storageClassName:  minio 
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/kubeless/minio"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minio-minio
spec:
  storageClassName:  minio
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi   