apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2017-10-13T01:07:50Z
  generation: 1
  labels:
    chart: jenkins-0.8.2
    component: jenkins-jenkins-master
    heritage: Tiller
    release: jenkins
  name: jenkins-jenkins
  namespace: default
  resourceVersion: "245654"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/jenkins-jenkins
  uid: eea6e500-afb2-11e7-9fb5-525400ada096
spec:
  replicas: 1
  selector:
    matchLabels:
      component: jenkins-jenkins-master
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/config: ab380374b5f6b43b39d6930d705f54e02b3ad88971d153f1b5fdf8b8f9c62921
        pod.alpha.kubernetes.io/init-containers: '[ { "name": "copy-default-config",
          "image": "jenkins/jenkins:lst", "imagePullPolicy": "Always", "command":
          [ "sh", "/var/jenkins_config/apply_config.sh" ], "volumeMounts": [ { "name":
          "jenkins-config", "mountPath": "/var/jenkins_config" }, { "name": "jenkins-home",
          "mountPath": "/var/jenkins_home" }, { "name": "plugin-dir", "mountPath":
          "/usr/share/jenkins/ref/plugins/" }, { "name": "secrets-dir", "mountPath":
          "/usr/share/jenkins/ref/secrets/" } ] } ]'
      creationTimestamp: null
      labels:
        app: jenkins-jenkins
        chart: jenkins-0.8.2
        component: jenkins-jenkins-master
        heritage: Tiller
        release: jenkins
    spec:
      containers:
      - args:
        - --argumentsRealm.passwd.$(ADMIN_USER)=$(ADMIN_PASSWORD)
        - --argumentsRealm.roles.$(ADMIN_USER)=admin
        env:
        - name: JAVA_OPTS
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: jenkins-admin-password
              name: jenkins-jenkins
        - name: ADMIN_USER
          valueFrom:
            secretKeyRef:
              key: jenkins-admin-user
              name: jenkins-jenkins
        image: jenkins/jenkins:lst
        imagePullPolicy: Always
        name: jenkins-jenkins
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 50000
          name: slavelistener
          protocol: TCP
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: jenkins-home
        - mountPath: /var/jenkins_config
          name: jenkins-config
          readOnly: true
        - mountPath: /usr/share/jenkins/ref/plugins/
          name: plugin-dir
        - mountPath: /usr/share/jenkins/ref/secrets/
          name: secrets-dir
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsUser: 0
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: nothing
      - configMap:
          defaultMode: 420
          name: jenkins-jenkins
        name: jenkins-config
      - emptyDir: {}
        name: plugin-dir
      - emptyDir: {}
        name: secrets-dir
      - name: jenkins-home
        persistentVolumeClaim:
          claimName: jenkins-jenkins
status:
  conditions:
  - lastTransitionTime: 2017-10-13T01:07:50Z
    lastUpdateTime: 2017-10-13T01:07:50Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
