apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
  labels:
    k8s-app: nginx
    tier: network-tools
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: nginx
    spec:      
      containers:
      - name: nginx       
        image: nginx        
        env: 
        - name: SSHD
          value: TURE
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace       
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name        
        ports:
        - containerPort: 80
        