apiVersion: extensions/v1beta1
kind: Deployment
metadata:  
  labels:
    run: nginx-sec
  name: nginx-sec 
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx-sec
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:     
      labels:
        name: nginx-sec
        tier: frontend
    spec:      
      containers:        
      - image: nginx
        imagePullPolicy: IfNotPresent
        name: nginx
        lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx","-s","quit"]
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
      restartPolicy: Always      
      terminationGracePeriodSeconds: 30
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 2000        
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: nginx-sec
  name: nginx-svc-sec 
spec: 
  ports:
  - port: 80
    protocol: TCP   
  selector:
    name: nginx-sec
  type: NodePort    
