apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-gitlab-pv
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /gitlab-data/gitlab-postgresqls-data
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gitlab-gitlab-ce-data
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
