apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-gitlab-postgresql-pv
  labels:
    type: local
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /gitlab-data/gitlab-postgresql
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gitlab-postgresql
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
